spring:
  datasource:
    #    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mariadb://localhost:3306/torch?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/torch-website?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: lijiayi20021027
    hikari:
      minimum-idle : 3
      maximum-pool-size: 5
      max-lifetime: 1800000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 139.186.170.118
    port: 6379
    database: 6
    password: keepacat